---
# tasks file for consul

- name: include assert.yml
  ansible.builtin.import_tasks: assert.yml
  run_once: yes
  delegate_to: localhost

- name: configure consul
  ansible.builtin.template:
    src: consul.hcl.j2
    dest: /etc/consul.d/consul.hcl
    owner: consul
    group: consul
    mode: "0644"
  notify:
    - restart consul

- name: configure consul service
  ansible.builtin.template:
    src: service.hcl.j2
    dest: /etc/cosul.d/service-{{ item.name }}-{{ item.port }}.hcl
    owner: consul
    group: consul
    mode: "0644"
  loop: "{{ consul_services }}"
  notify:
    - restart consul
  when:
    - consul_services is defined

- name: start and enable consul
  ansible.builtin.service:
    name: consul
    state: started
    enabled: true
